### ISSUE TITLE
Update Logos

### ISSUE THREAD

**Issue by Sotin0258** [GNimrodG/car-reg-ui#1]

**Comment by Sotin0258** [comment]
![image](https://user-images.githubusercontent.com/62951372/205428362-13a524bc-0b36-4525-ad0b-b804d7a54ee3.png)

**Comment by GNimrodG** [comment]
![image](https://user-images.githubusercontent.com/25616517/205909889-da4cb453-2ac1-4795-bb88-2085c946b7c7.png)
Cannot reproduce the issue.
